name: covid19-macrophages
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-scran
  - bioconductor-batchelor=1.14.0
  - bioconductor-clusterProfiler
  - bioconductor-slingshot
  - r-seurat=4.3.0.1
  - r-seuratobject
  - r-hdf5r
  - r-leiden
  - r-viridis=0.6.4
  - r-pheatmap
  - r-readr
  - r-readxl
  - r-uwot=0.1.16
  - r-rgl
  - r-ggpubr
  - r-ggalluvial
  - r-ggnewscale
  - leidenalg=0.8.4
  - pandas
